OPENAI_API_KEY = "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"

SF_USER = 'R33'
SF_PASSWORD = 'UuUXhSmi5@V6NGy'
SF_ACCOUNT = 'ln38567.sa-east-1.aws'
SF_WAREHOUSE = 'COMPUTE_WH'
SF_DATABASE = 'SHOPPING_DB'
SF_SCHEMA = 'ESQUEMA_PRINCIPAL'
SF_ROLE = 'ACCOUNTADMIN'
